[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # riot syntax
repo = 'ryym/vim-riot'
on_ft = 'tag'

[[plugins]] # TMUX
repo = 'tmux-plugins/vim-tmux'
on_ft = 'tmux'

[[plugins]]
repo  = 'Quramy/tsuquyomi'
on_ft = ['typescript', 'ts']

[[plugins]] # plantuml-syntax
repo = 'aklt/plantuml-syntax'
on_ft = 'pu'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['md', 'markdown']

[[plugins]]
repo = 'violetyk/neocomplete-php.vim'
hook_add = '''
let g:neocomplete_php_locale = 'ja'
'''
on_ft = ['php']

# <CTRL> + Pでphp docを挿入する
[[plugins]]
repo = 'vim-scripts/PDV--phpDocumentor-for-Vim'
hook_add = '''
inoremap <C-P> <Esc>:call PhpDocSingle()<CR>i
nnoremap <C-P> :call PhpDocSingle()<CR>
vnoremap <C-P> :call PhpDocSingle()<CR>
'''
on_ft = ['php']

# emmetをvimで
[[plugins]]
repo  = 'mattn/emmet-vim'
on_ft = ['css','html']

[[plugins]]
repo  = 'leafgarland/typescript-vim'
on_ft = ['typescript', 'ts']

[[plugins]] # vue syntax
repo = 'posva/vim-vue'
on_ft = 'vue'
